#!/usr/bin/env bash
# This script configures a new nginx server and adds a header

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sed -i 's/http {/&\n\tadd_header X-Served-By $HOSTNAME/;' /etc/nginx/nginx.conf
sudo service nginx restart
